name: Env-TEARDOWN

env:
  LOCATION: centralus
  APP_PREFIX: Wbademo

on:
  issue_comment:
    types: [ created, edited ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '/teardown')

    steps:
    # checkout - remember we have to check out the PR code!
    - uses: actions/checkout@v2
    - name: Checkout PR code
      uses: dawidd6/action-checkout-pr@v1
      with:
        pr: ${{ github.event.issue.number }}

    - name: Create starting comment
      uses: peter-evans/create-or-update-comment@v1
      with:
        token: ${{ secrets.TOKEN }}
        issue-number: ${{ github.event.issue.number }}
        body: |
          Hey, @${{ github.event.comment.user.login }}!
          :rocket: Tearding down is beginning! :rocket:

    - name: 'Login via Az module'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true

    - name: Teardown environment
      uses: azure/powershell@v1
      with:
        azPSVersion: latest
        inlineScript: |
          Write-Verbose "Tearing down..." -Verbose
          $rgs = Get-AzResourceGroup | Where-Object { $_.Name -like "${{ env.APP_PREFIX }}" }
          
          foreach ($rg in $rgs) {
             Write-Verbose "Deleting resource group - '$(rg.Name)'" -Verbose
             $rg | Remove-AzResourceGroup -Force 
          }

    - name: Create completed comment
      uses: peter-evans/create-or-update-comment@v1
      with:
        token: ${{ secrets.TOKEN }}
        issue-number: ${{ github.event.issue.number }}
        body: |
          Hey, @${{ github.event.comment.user.login }}!
          :tada: Teardown completed! :tada:
